# Lefthook configuration for PagerMon Ingest Core
# @see https://github.com/evilmartians/lefthook

pre-commit:
  commands:
    lint-and-format:
      glob: "**/*.{js,mjs,json,md}"
      run: npx lint-staged --verbose
      skip:
        - merge
        - rebase

pre-push:
  commands:
    test:
      glob: "**/*.js"
      run: npm run test-ci
      skip:
        - merge
        - rebase

commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit $GIT_PARAMS
